baseURL = "http://example.org/"
languageCode = "fr-FR"
title = "Quentin GARRAUD"
theme = "garraud-theme"
enableRobotsTXT = "false"


#### Plugins ####
[params.plugins]
    ## Styles plugins ##
    [[params.plugins.styles]]
    URL = "/styles/index.css"

    ## Script plugins ##
    [[params.plugins.js]]
    URL = "/scripts/menu.js"


##### Paramètres par défauts #####
[params]
    description = "Développeur Front End en alternance au CESI de Bordeaux chez Solidnames."
    favicon = "/images/favicon.png"
    slogan = "Développeur Front End chez Solidnames"

