baseURL = "https://dev.garraud.fr/"
languageCode = "fr-FR"
title = "Quentin GARRAUD"
theme = "garraud-theme"
enableRobotsTXT = "false"
disableKinds = ["term"]

#### Plugins ####
[params.plugins]
    ## Styles plugins ##
    [[params.plugins.styles]]
    URL = "/styles/index.css"

    ## Script plugins ##
    [[params.plugins.js]]
    URL = "/scripts/menu.js"

#### Taxonomies ####
[taxonomies]
    category = "categories"


[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Les articles"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "Les projets"
    url = "/projets/"
    weight = 3

  [[menu.main]]
    name = "Boîte à outils"
    url = "/la-boite-a-outils-du-web/"
    weight = 4

##### Paramètres par défauts #####
[params]
    description = "Développeur Front End en alternance au CESI de Bordeaux chez Solidnames."
    favicon = "/images/favicon.png"
    slogan = "Développeur Front End chez Solidnames"